#!/bin/bash
MANIFEST=https://github.com/DerpFest-AOSP/manifest.git
BRANCH=13
CODENAME=enchilada
BRAND=oneplus
DT_LINK=https://github.com/Beta-boom/derp_android_device_oneplus_enchilada.git
DCT_LINK=https://github.com/Beta-boom/derp_android_device_oneplus_sdm845-common.git
KT_LINK=https://github.com/Beta-boom/kernel_oneplus_sdm845.git
VT_LINK=https://github.com/Beta-boom/vendor_oneplus_enchilada.git
VCT_LINK=https://github.com/Beta-boom/vendor_oneplus_sdm845-common.git
HT_LINK=https://github.com/Beta-boom/android_hardware_oneplus.git

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Josep Valencia"
git config --global user.email "josep200508@hotmail.com"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Clone
git clone $DT_LINK --single-branch -b lineage-20 --depth=1 device/$BRAND/$CODENAME
git clone $DCT_LINK --single-branch -b lineage-20 --depth=1 device/$BRAND/sdm845-common
git clone $KT_LINK --single-branch -b thirteen --depth=1 kernel/oneplus/sdm845
git clone $VT_LINK --single-branch -b thirteen --depth=1 vendor/$BRAND/$CODENAME
git clone $VCT_LINK --single-branch -b thirteen --depth=1 vendor/$BRAND/sdm845-common
git clone $HT_LINK --single-branch -b Tulip --depth=1 hardware/$BRAND
git clone https://github.com/HemantSachdeva/proton-clang --depth=1 prebuilts/clang/host/linux-x86/clang-proton
# rm device/xiaomi/laurel_sprout/vendorsetup.sh # Yeah I will take care of that here myself
# rm -rf vendor/qcom/opensource/commonsys-intf/display && git clone https://github.com/HemantSachdeva/vendor_qcom_opensource_display-commonsys-intf vendor/qcom/opensource/commonsys-intf/display &&
# rm -rf vendor/qcom/opensource/wfd-commonsys && git clone https://github.com/HemantSachdeva/vendor_qcom_opensource_wfd-commonsys vendor/qcom/opensource/wfd-commonsys
